export const addictions = [
  "Alcohol",
  "Nicotine",
  "Caffeine",
  "Marijuana",
  "Cocaine",
  "Heroin",
  "Methamphetamine",
  "Prescription Drugs",
  "Gambling",
  "Internet",
  "Social Media",
  "Sex",
  "Pornography",
  "Food",
  "Sugar",
  "Work",
  "Exercise",
  "Shopping",
  "Video Games",
  "Television",
  "Smartphones",
  "Painkillers",
  "Hallucinogens",
  "Inhalants",
  "Energy Drinks",
  "Tobacco",
  "Love",
  "Adrenaline",
  "Plastic Surgery",
  "Benzodiazepines",
];
